language: objective-c
git:
  depth: 2
node_js:
  - "0.10"
install:
  - npm install -g cordova
  - npm install -g cordova-paramedic
  - npm install -g ios-sim
script:
  - cordova-paramedic --platform ios --plugin ${TRAVIS_BUILD_DIR}
